### ISSUE TITLE
index out of range exception

### ISSUE THREAD

**Issue by ChristophKnapp** [jonfunk21/ProteusAI#15]
Hi 
I'm running some code in a wrapper script based on the code found in the demo and example scripts here in this repository. ProteusAI is imported in my python virtual environment. Zero shot works fine but when I try to run the best candidate variants with esm_fold, I get the following error.

```
top_i.esm_fold(dest=dest)  
```
.venv/lib/python3.8/site-packages/proteusAI/Protein/protein.py", line 464, in esm_fold
    chain = self.chains[0]
IndexError: list index out of range

Looking at the protein.py script in the esm_fold function.

```
if chain is None:
      chain = self.chains[0]
```

self.chains is always an empty list at this point, hence the index out of range. 

I'm not sure whether this is a bug or  I'm doing something wrong.

Thanks for your help

**Comment by jonfunk21** [comment]
Hi Christoph,

thanks for pointing out the bug! The folding functionality needed some more attention, but it is fixed now in the current release (v0.0.7), together with some more demos!

I hope it works for you, if not, please reach out.

Cheers
