### ISSUE TITLE
Question about demo

### ISSUE THREAD

**Issue by zhang-bo-lilly** [jonfunk21/ProteusAI#9]
Hello, I ran into some error when stepping through the [demo](https://github.com/jonfunk21/ProteusAI/blob/main/demo.ipynb) notebook and the [demo.py](https://github.com/jonfunk21/ProteusAI/blob/main/demo/demo.py) file. 

In each case, no user has been created. When I execute 

```python
library = pai.Library(user='guest', overwrite=False) 
``` 

The following error is thrown 
```shell
TypeError: __init__() got an unexpected keyword argument 'overwrite'
```

When I try 

https://github.com/jonfunk21/ProteusAI/blob/a7d23555d53f39499a48e8da60dc4749fbbd21fc/demo/demo.py#L12-L13

The following error is thrown 

```shell
TypeError: object of type 'NoneType' has no len()
``` 

from 

https://github.com/jonfunk21/ProteusAI/blob/a7d23555d53f39499a48e8da60dc4749fbbd21fc/src/proteusAI/Library/library.py#L221

because 

https://github.com/jonfunk21/ProteusAI/blob/a7d23555d53f39499a48e8da60dc4749fbbd21fc/src/proteusAI/Library/library.py#L83

Appreciate suggestions on resolving this error.

**Comment by jonfunk21** [comment]
The source of the error is likely an error in the package, I am going to publish a new version of the Python package very soon, you can then update the package.

Alternatively, you can fix the error manually by doing the following:

```
import os
import sys

import proteusAI as pai

print(os.getcwd())
sys.path.append("src/")


# will initiate storage space - else in memory
datasets = ["demo/demo_data/Nitric_Oxide_Dioxygenase_raw.csv"]
y_columns = ["Data"]

results_dictionary = {}
for dataset in datasets:
    for y in y_columns:
        # load data from csv or excel: x should be sequences, y should be labels, y_type class or num
        library = pai.Library(
            source=dataset,
            seqs_col="Sequence",
            y_col=y,
            y_type="num",
            names_col="Description",
        )

    print(library.user)
```

This should print the location where temporary data is stored and where the package is installed, and will look something like this:

```
'/home/<user>/.local/lib/python3.8/site-packages/proteusAI/Library/../../../usrs/guest'
```

If you open the terminal, you can copy the proteusAI source code to that location, which will update the package to its current state:

```
cp -r src/proteusAI/ /home/<user>/.local/lib/python3.8/site-packages/
```

I hope this helps, let me know if you need further assistance!

**Comment by jonfunk21** [comment]
Hi, the new release should have fixed the problems, you can try to reinstall it :)
